### ISSUE TITLE
Triple bracket unescaping not respected as parameter

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-component#23] opened 2017-03-28 11:07 UTC
This doesn't work:
```
<my-component @html={{{myHtml}}} />
```

But this does:
```
{{{myHtml}}}
```

**Comment by tomdale** [comment] 2017-03-28 11:36
@asakusuma Why would you expect to be able to escape something that does not get rendered into DOM?

**Comment by asakusuma** [comment] 2017-03-28 11:38
Sorry for not being more clear, but if inside `my-component` you want to unescape, you can't:

```Handlebars
<!-- my-component.hbs -->
<div>
{{{@html}}}
</div>
```

**Comment by mmun** [comment] 2017-03-30 03:17
I can't reproduce this. Works fine for me.

**Comment by rwjblue** [comment] 2018-03-05 14:35
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!

**Closed by rwjblue** 2018-03-05 14:35 UTC
